In [2]:
!pip install nltk

  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434681 sha256=295958a23eb27c66a38b851a0608336703f9321a099e339fdff5de1ee20ab676
  Stored in directory: c:\users\huawe~1\appdata\local\pip\cache\wheels\de\5e\42\64abaeca668161c3e2cecc24f864a8fc421e3d07a104fc8a51
Successfully built nltk


In [3]:
!pip install textblob

In [5]:
import pandas as pd 
data = pd.read_csv('datafiniti-hotel-reviews/Datafiniti_Hotel_Reviews.csv')

In [6]:
data

id             dateAdded           dateUpdated  \
0     AVwc252WIN2L1WUfpqLP  2016-10-30T21:42:42Z  2018-09-10T21:06:27Z   
1     AVwc252WIN2L1WUfpqLP  2016-10-30T21:42:42Z  2018-09-10T21:06:27Z   
2     AVwc252WIN2L1WUfpqLP  2016-10-30T21:42:42Z  2018-09-10T21:06:27Z   
3     AVwdOclqIN2L1WUfti38  2015-11-28T19:19:35Z  2018-09-10T21:06:16Z   
4     AVwdOclqIN2L1WUfti38  2015-11-28T19:19:35Z  2018-09-10T21:06:16Z   
...                    ...                   ...                   ...   
9995  AVwd4TMv_7pvs4fz-Ers  2016-03-24T11:44:15Z  2018-01-01T00:00:46Z   
9996  AVwdRp4DIN2L1WUfuGZZ  2015-10-26T23:03:02Z  2018-01-01T00:00:44Z   
9997  AVwd1TbkByjofQCxs6FH  2016-06-11T03:12:23Z  2018-01-01T00:00:44Z   
9998  AVwdHbizIN2L1WUfsXto  2016-12-13T03:44:36Z  2018-01-01T00:00:43Z   
9999  AVwddMfdIN2L1WUfwAue  2016-06-22T19:07:21Z  2018-01-01T00:00:43Z   

                  address                                         categories  \
0       5921 Valencia Cir  Hotels,Hotels and motels,Hotel and motel reser...   
1       5921 Valencia Cir  Hotels,Hotels and motels,Hotel and motel reser...   
2       5921 Valencia Cir  Hotels,Hotels and motels,Hotel and motel reser...   
3          7520 Teague Rd  Hotels,Hotels and motels,Travel agencies and b...   
4          7520 Teague Rd  Hotels,Hotels and motels,Travel agencies and b...   
...                   ...                                                ...   
9995     215 S Pacific St                        Hotel,Hotels,Lodging,Motels   
9996         669 Route 6a                                       Hotel,Hotels   
9997   702 W Appleway Ave  Hotel,Hotel, Motel, and Building,Hotels,Lodgin...   
9998  2295 N Highland Ave  Hotel,Hotels Motels,Budget Hotels,Hotels & Motels   
9999    3811 Minnesota Dr      Hotel,Motels,Lodging,Hotels,Hotels and Motels   

                  primaryCategories             city country  \
0     Accommodation & Food Services  Rancho Santa Fe      US   
1     Accommodation & Food Services  Rancho Santa Fe      US   
2     Accommodation & Food Services  Rancho Santa Fe      US   
3     Accommodation & Food Services          Hanover      US   
4     Accommodation & Food Services          Hanover      US   
...                             ...              ...     ...   
9995  Accommodation & Food Services   Rockaway Beach      US   
9996  Accommodation & Food Services    East Sandwich      US   
9997  Accommodation & Food Services    Coeur d'Alene      US   
9998  Accommodation & Food Services          Jackson      US   
9999  Accommodation & Food Services        Anchorage      US   

                                               keys   latitude  ...  \
0     us/ca/ranchosantafe/5921valenciacir/359754519  32.990959  ...   
1     us/ca/ranchosantafe/5921valenciacir/359754519  32.990959  ...   
2     us/ca/ranchosantafe/5921valenciacir/359754519  32.990959  ...   
3            us/md/hanover/7520teaguerd/-2043779672  39.155929  ...   
4            us/md/hanover/7520teaguerd/-2043779672  39.155929  ...   
...                                             ...        ...  ...   
9995  us/or/rockawaybeach/215spacificst/-1035432852  45.611260  ...   
9996      us/ma/eastsandwich/669route6a/-1480952475  41.729390  ...   
9997   us/id/coeurd'alene/702wapplewayave/210547670  47.699930  ...   
9998      us/tn/jackson/2295nhighlandave/1759289930  35.666390  ...   
9999      us/ak/anchorage/3811minnesotadr/806029870  61.185310  ...   

                                       reviews.dateSeen reviews.rating  \
0     2016-08-03T00:00:00Z,2016-07-26T00:00:00Z,2016...            5.0   
1     2016-08-02T00:00:00Z,2016-08-26T00:00:00Z,2016...            5.0   
2     2016-11-15T00:00:00Z,2016-08-23T00:00:00Z,2016...            5.0   
3             2016-05-21T00:00:00Z,2016-07-31T00:00:00Z            2.0   
4                                  2016-07-31T00:00:00Z            5.0   
...                                                 ...            ...   
9995                              

In [4]:
data["reviews.rating"].replace(1.0, value = "negatif", inplace = True)
data["reviews.rating"].replace(2.0, value = "negatif", inplace = True)

In [5]:
data["reviews.rating"].replace(4.0, value = "pozitif", inplace = True)
data["reviews.rating"].replace(5.0, value = "pozitif", inplace = True)

In [6]:
data['reviews.rating']

0       pozitif
1       pozitif
2       pozitif
3       negatif
4       pozitif
         ...   
9995          3
9996    pozitif
9997    pozitif
9998    negatif
9999    negatif
Name: reviews.rating, Length: 10000, dtype: object

In [6]:
data = data[(data['reviews.rating'] == "negatif") | (data['reviews.rating'] == "pozitif")] 

In [8]:
data['reviews.rating']

0       pozitif
1       pozitif
2       pozitif
3       negatif
4       pozitif
         ...   
9994    pozitif
9996    pozitif
9997    pozitif
9998    negatif
9999    negatif
Name: reviews.rating, Length: 7914, dtype: object

In [9]:
data.groupby('reviews.rating').count()

id  dateAdded  dateUpdated  address  categories  \
reviews.rating                                                      
negatif         1133       1133         1133     1133        1133   
pozitif         6781       6781         6781     6781        6781   

                primaryCategories  city  country  keys  latitude  ...  \
reviews.rating                                                    ...   
negatif                      1133  1133     1133  1133      1133  ...   
pozitif                      6781  6781     6781  6781      6781  ...   

                reviews.date  reviews.dateSeen  reviews.sourceURLs  \
reviews.rating                                                       
negatif                 1133              1133                1133   
pozitif                 6781              6781                6781   

                reviews.text  reviews.title  reviews.userCity  \
reviews.rating                                                  
negatif                 1133           1133               450   
pozitif                 6781           6781              3224   

                reviews.userProvince  reviews.username  sourceURLs  websites  
reviews.rating                                                                
negatif                          316              1133        1133      1133  
pozitif                         2078              6781        6781      6781  

[2 rows x 24 columns]

In [7]:
df = pd.DataFrame()
df["comment"] = data["reviews.text"]
df["sentiment"] = data["reviews.rating"]

In [11]:
df

comment sentiment
0     Our experience at Rancho Valencia was absolute...   pozitif
1     Amazing place. Everyone was extremely warm and...   pozitif
2     We booked a 3 night stay at Rancho Valencia to...   pozitif
3     Currently in bed writing this for the past hr ...   negatif
4     I live in Md and the Aloft is my Home away fro...   pozitif
...                                                 ...       ...
9994  Small town on the state route - unexpected del...   pozitif
9996  I live close by, and needed to stay somewhere ...   pozitif
9997  Rolled in 11:30 laid out heads down woke up to...   pozitif
9998  Absolutely terrible..I was told I was being gi...   negatif
9999  Filthy, outdated, noisy neighbours, but this w...   negatif

[7914 rows x 2 columns]

In [8]:
#buyuk-kucuk donusumu
df['comment'] = df['comment'].apply(lambda x: " ".join(x.lower() for x in x.split()))
#noktalama işaretleri
df['comment'] = df['comment'].str.replace('[^\w\s]','')
#sayılar
df['comment'] = df['comment'].str.replace('\d','')
#stopwords
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords
sw = stopwords.words('english')
df['comment'] = df['comment'].apply(lambda x: " ".join(x for x in x.split() if x not in sw))
#seyreklerin silinmesi
sil = pd.Series(' '.join(df['comment']).split()).value_counts()[-1000:]
df['comment'] = df['comment'].apply(lambda x: " ".join(x for x in x.split() if x not in sil))
#lemmi
from textblob import Word
#nltk.download('wordnet')
df['comment'] = df['comment'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()])) 

In [13]:
df

comment sentiment
0     experience rancho valencia absolutely perfect ...   pozitif
1     amazing place everyone extremely warm welcomin...   pozitif
2     booked night stay rancho valencia play tennis ...   pozitif
3     currently bed writing past hr dog barking sque...   negatif
4     live md aloft home away homewe stayed night st...   pozitif
...                                                 ...       ...
9994  small town state route unexpected delight hote...   pozitif
9996  live close needed stay somewhere night due ren...   pozitif
9997  rolled laid head woke continental breakfast ro...   pozitif
9998  absolutely terriblei told given non smoking ro...   negatif
9999  filthy outdated noisy worst nearly eaten bed b...   negatif

[7914 rows x 2 columns]

In [9]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(df["comment"],
                                                                   df["sentiment"], 
                                                                    random_state = 1)

In [16]:
train_y[0:5]

8630    pozitif
4602    pozitif
7930    pozitif
9334    pozitif
1549    negatif
Name: sentiment, dtype: object

In [10]:
encoder = preprocessing.LabelEncoder()

In [11]:
train_y = encoder.fit_transform(train_y)
test_y = encoder.fit_transform(test_y)

In [19]:
train_y[0:5]

array([1, 1, 1, 1, 0])

In [20]:
test_y[0:5]

array([0, 1, 1, 1, 0])

In [12]:
# count vektor
vectorizer = CountVectorizer() #ilk başta oluşturduğumuz train_x'i bozmamak için yeni vectorizer oluşturduk.
vectorizer.fit(train_x)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [13]:
x_train_count = vectorizer.transform(train_x)
x_test_count = vectorizer.transform(test_x)

In [14]:
vectorizer.get_feature_names()[0:5]

['aaa', 'aamiaisen', 'aaron', 'aarp', 'ab']

In [15]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)


# tf-idf wordlevel : 

In [16]:
tf_idf_word_vectorizer = TfidfVectorizer() #ilk başta oluşturduğumuz train_x'i bozmamak için yeni vectorizer oluşturduk.
tf_idf_word_vectorizer.fit(train_x)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [17]:
x_train_tf_idf_word = tf_idf_word_vectorizer.transform(train_x)
x_test_tf_idf_word = tf_idf_word_vectorizer.transform(test_x)

In [18]:
tf_idf_word_vectorizer.get_feature_names()[0:5]

['aaa', 'aamiaisen', 'aaron', 'aarp', 'ab']

In [19]:
x_train_tf_idf_word.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# ngram level tf-idf : 

In [20]:
tf_idf_ngram_vectorizer = TfidfVectorizer(ngram_range = (2,3))
tf_idf_ngram_vectorizer.fit(train_x)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(2, 3), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [21]:
x_train_tf_idf_ngram = tf_idf_ngram_vectorizer.transform(train_x)
x_test_tf_idf_ngram = tf_idf_ngram_vectorizer.transform(test_x)

# characters level tf-idf

In [22]:
tf_idf_chars_vectorizer = TfidfVectorizer(analyzer = "char", ngram_range = (2,3))
tf_idf_chars_vectorizer.fit(train_x)

TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(2, 3), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [23]:
x_train_tf_idf_chars = tf_idf_chars_vectorizer.transform(train_x)
x_test_tf_idf_chars = tf_idf_chars_vectorizer.transform(test_x)

# makine öğrenmesi ile sentiment sınıflandırılması

# logistic regression

In [40]:
loj = linear_model.LogisticRegression()
loj_model = loj.fit(x_train_count, train_y)
accuracy = model_selection.cross_val_score(loj_model, 
                                           x_test_count, 
                                           test_y, 
                                           cv = 10).mean()

print("Count Vectors Doğruluk Oranı:", accuracy)

Count Vectors Doğruluk Oranı: 0.9181382351433113


In [25]:
loj = linear_model.LogisticRegression()
loj_model = loj.fit(x_train_tf_idf_word,train_y)
accuracy = model_selection.cross_val_score(loj_model, 
                                           x_test_tf_idf_word, 
                                           test_y, 
                                           cv = 10).mean()

print("Word-Level TF-IDF Doğruluk Oranı:", accuracy)

Word-Level TF-IDF Doğruluk Oranı: 0.8762010972670872


In [26]:
loj = linear_model.LogisticRegression()
loj_model = loj.fit(x_train_tf_idf_ngram,train_y)
accuracy = model_selection.cross_val_score(loj_model, 
                                           x_test_tf_idf_ngram, 
                                           test_y, 
                                           cv = 10).mean()

print("N-GRAM TF-IDF Doğruluk Oranı:", accuracy)

N-GRAM TF-IDF Doğruluk Oranı: 0.859526739475978


In [27]:
loj = linear_model.LogisticRegression()
loj_model = loj.fit(x_train_tf_idf_chars,train_y)
accuracy = model_selection.cross_val_score(loj_model, 
                                           x_test_tf_idf_chars, 
                                           test_y, 
                                           cv = 10).mean()

print("CHARLEVEL TF-IDF Doğruluk Oranı:", accuracy)

CHARLEVEL TF-IDF Doğruluk Oranı: 0.8868071578731478


## Naive Bayes

In [28]:
nb = naive_bayes.MultinomialNB()
nb_model = nb.fit(x_train_count,train_y)
accuracy = model_selection.cross_val_score(nb_model, 
                                           x_test_count, 
                                           test_y, 
                                           cv = 10).mean()

print("Count Vectors Doğruluk Oranı:", accuracy)

Count Vectors Doğruluk Oranı: 0.8989463159513921


In [29]:
nb = naive_bayes.MultinomialNB()
nb_model = nb.fit(x_train_tf_idf_word,train_y)
accuracy = model_selection.cross_val_score(nb_model, 
                                           x_test_tf_idf_word, 
                                           test_y, 
                                           cv = 10).mean()

print("Word-Level TF-IDF Doğruluk Oranı:", accuracy)

Word-Level TF-IDF Doğruluk Oranı: 0.859526739475978


In [30]:
nb = naive_bayes.MultinomialNB()
nb_model = nb.fit(x_train_tf_idf_ngram,train_y)
accuracy = model_selection.cross_val_score(nb_model, 
                                           x_test_tf_idf_ngram, 
                                           test_y, 
                                           cv = 10).mean()

print("N-GRAM TF-IDF Doğruluk Oranı:", accuracy)

N-GRAM TF-IDF Doğruluk Oranı: 0.859526739475978


In [31]:
nb = naive_bayes.MultinomialNB()
nb_model = nb.fit(x_train_tf_idf_chars,train_y)
accuracy = model_selection.cross_val_score(nb_model, 
                                           x_test_tf_idf_chars, 
                                           test_y, 
                                           cv = 10).mean()

print("CHARLEVEL TF-IDF Doğruluk Oranı:", accuracy)

CHARLEVEL TF-IDF Doğruluk Oranı: 0.859526739475978


# random forest

In [33]:
rf = ensemble.RandomForestClassifier()
rf_model = rf.fit(x_train_count,train_y)
accuracy = model_selection.cross_val_score(rf_model, 
                                           x_test_count, 
                                           test_y, 
                                           cv = 10).mean()

print("Count Vectors Doğruluk Oranı:", accuracy)

Count Vectors Doğruluk Oranı: 0.8908578167461416


In [34]:
rf = ensemble.RandomForestClassifier()
rf_model = rf.fit(x_train_tf_idf_word,train_y)
accuracy = model_selection.cross_val_score(rf_model, 
                                           x_test_tf_idf_word, 
                                           test_y, 
                                           cv = 10).mean()

print("Word-Level TF-IDF Doğruluk Oranı:", accuracy)

Word-Level TF-IDF Doğruluk Oranı: 0.8807465518125417


In [35]:
rf = ensemble.RandomForestClassifier()
rf_model = rf.fit(x_train_tf_idf_ngram,train_y)
accuracy = model_selection.cross_val_score(rf_model, 
                                           x_test_tf_idf_ngram, 
                                           test_y, 
                                           cv = 10).mean()

print("N-GRAM TF-IDF Doğruluk Oranı:", accuracy)

N-GRAM TF-IDF Doğruluk Oranı: 0.8610418909911296


In [36]:
rf = ensemble.RandomForestClassifier()
rf_model = rf.fit(x_train_tf_idf_chars,train_y)
accuracy = model_selection.cross_val_score(rf_model, 
                                           x_test_tf_idf_chars, 
                                           test_y, 
                                           cv = 10).mean()

print("CHARLEVEL TF-IDF Doğruluk Oranı:", accuracy)

CHARLEVEL TF-IDF Doğruluk Oranı: 0.8666000102548326


In [60]:
#yeni_yorum = pd.Series("this hotel is very nice and good i like it")

yeni_yorum = pd.Series("dirty and noisy rooms.")

In [61]:
# count vektorizer'i oluşturdum. Yukarıda örneği var.
v = CountVectorizer()
v.fit(train_x)
yeni_yorum = v.transform(yeni_yorum)

In [63]:
#lineer regressions ile oluşturduğumuz modele yeni yorum cümlesi verdik ve 1/0 döndürür.
sonuc = loj_model.predict(yeni_yorum)
if sonuc == 0:
    print("negatif")
else:
    print("pozitif")

negatif
